[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_solana_tutorial = "GMEM4oFc9kZnvWQqocEfNxVyiaGE2yARZcYW2oaucXd7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/nft-solana-tutorial.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
